<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="LT-Harsh" failures="1" tests="1" name="Test(failed)" time="13.662" errors="0" timestamp="2025-07-10T11:02:07 IST">
  <testcase classname="testCases.TC001" name="RedirectionToEditAccount" time="10.058">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC001.RedirectionToEditAccount(TC001.java:116)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- RedirectionToEditAccount -->
  <testcase classname="testCases.TC001" name="redirectionToEditAccount" time="0.0">
    <ignored/>
  </testcase> <!-- redirectionToEditAccount -->
  <testcase classname="testCases.TC001" name="homePageTestMethod" time="0.0">
    <ignored/>
  </testcase> <!-- homePageTestMethod -->
  <testcase classname="testCases.TC001" name="editAccounts" time="0.0">
    <ignored/>
  </testcase> <!-- editAccounts -->
  <testcase classname="testCases.TC001" name="registerPageTestMethod" time="0.0">
    <ignored/>
  </testcase> <!-- registerPageTestMethod -->
</testsuite> <!-- Test(failed) -->
